"""file size field added to vacancy model

Revision ID: 33dc21f6f964
Revises: 4ca3886d3621
Create Date: 2025-12-04 17:19:47.395151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dc21f6f964'
down_revision: Union[str, Sequence[str], None] = '4ca3886d3621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_applications', sa.Column('cv_filesize', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_applications', 'cv_filesize')
    # ### end Alembic commands ###
